r"""构建 NestPack 的 Windows GUI/CLI exe 与 Linux CLI 可执行文件。

各平台使用本机 PyInstaller 构建单文件程序。
外层 PowerShell / Bash 脚本只负责选择 Python 解释器并转交参数。

用法（在项目根目录执行）：
    python scripts\build.py              # 构建 Windows exe
    python scripts\build.py --yes        # 自动结束占用进程，不询问
    python scripts\build.py --no-kill    # 检测到占用进程直接失败退出
    python3 scripts/build.py             # 构建 Linux CLI 可执行文件
"""

from __future__ import annotations

import argparse
import os
import shutil
import struct
import subprocess
import sys
from importlib import metadata
from pathlib import Path

# 脚本位于 scripts/ 下，项目根是其上一级。
ROOT = Path(__file__).resolve().parent.parent
# 直接 python scripts\build.py 运行时 sys.path 里没有项目根，补上以便导入 gui 包。
sys.path.insert(0, str(ROOT))

from core.legal import LEGAL_DOCUMENTS  # noqa: E402

# PyInstaller 分析缓存放项目内的 build 目录（已被 gitignore）。
CACHE_DIR = ROOT / "build" / "pyinstaller-cache"
# 打包时从应用图标生成多尺寸 EXE 图标。
ICON_PATH = ROOT / "build" / "app.ico"

# (产物文件名, PyInstaller --name, 入口脚本, 窗口模式开关)。
# --windowed 目标构建时会生成裁剪过的 spec 以瘦身，--console 目标不做裁剪。
TARGETS = (
    ("NestPack.exe", "NestPack", "gui/__main__.py", "--windowed"),
    ("nestpack-cli.exe", "nestpack-cli", "cli/__main__.py", "--console"),
)

# 每个目标生成的 spec 模板。用 @占位符@ 替换，避免与 Python 花括号冲突。
# GUI 目标在 Analysis 之后筛除未使用的 Qt 二进制与翻译文件。
SPEC_TEMPLATE = r'''# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py. 手动修改会被下次构建覆盖。

import re

# GUI 使用 QtCore/QtGui/QtWidgets、QtSvg/QtSvgWidgets/QtXml。
# 以下列表排除无需纳入构建的 PySide6 模块。
_EXCLUDED_QT_MODULES = [
    "PySide6.QtNetwork",
    "PySide6.QtPdf", "PySide6.QtPdfWidgets", "PySide6.QtQuick",
    "PySide6.QtQuickWidgets", "PySide6.QtQuick3D", "PySide6.QtQuickControls2",
    "PySide6.QtQml", "PySide6.QtVirtualKeyboard", "PySide6.QtOpenGL",
    "PySide6.QtOpenGLWidgets", "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets", "PySide6.QtPrintSupport", "PySide6.QtSql",
    "PySide6.QtTest", "PySide6.QtDesigner", "PySide6.QtHelp",
    "PySide6.QtUiTools", "PySide6.QtDBus",
    "PySide6.QtConcurrent", "PySide6.Qt3DCore", "PySide6.Qt3DRender",
    "PySide6.QtCharts", "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineQuick",
    "PySide6.QtWebSockets", "PySide6.QtWebView", "PySide6.QtHttpServer",
    "PySide6.QtWebChannel", "PySide6.QtPositioning", "PySide6.QtLocation",
    "PySide6.QtBluetooth", "PySide6.QtSensors", "PySide6.QtSerialBus",
    "PySide6.QtSerialPort", "PySide6.QtScxml", "PySide6.QtStateMachine",
    "PySide6.QtTextToSpeech", "PySide6.QtSpatialAudio",
    "PySide6.QtDataVisualization", "PySide6.QtGraphs",
    "PySide6.QtGraphsWidgets", "PySide6.QtRemoteObjects",
    "PySide6.QtNetworkAuth", "PySide6.QtNfc", "PySide6.QtAxContainer",
    "PySide6.QtCanvasPainter",
]

# 用不到的 Qt DLL 与插件：QML/Quick/Pdf/VirtualKeyboard/Network/OpenGL、
# OpenGL 软件渲染器、OpenSSL，以及 Windows 平台和 SVG 图标之外的插件。
_UNWANTED_BINARIES = re.compile(
    r"(opengl32sw|libEGL|libGLESv2|d3dcompiler_\d+|"
    r"Qt6(Network|Pdf|Quick|Qml\w*|VirtualKeyboard|OpenGL)|"
    r"Qt(Network|Pdf|Quick|Qml\w*|VirtualKeyboard|OpenGL)|"
    r"libcrypto-3|libssl-3)\.\w+$",
    re.IGNORECASE,
)
_KEEP_PLUGIN = re.compile(
    r"^PySide6/plugins/(?:platforms/qwindows|imageformats/qsvg|iconengines/qsvgicon)\.dll$"
)

a = Analysis(
    ['@ENTRY@'],
    pathex=[@ROOT@],
    binaries=[],
    datas=@DATA@,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=_EXCLUDED_QT_MODULES,
    noarchive=False,
    optimize=0,
)
if @SLIM@:
    # 保留 Windows 平台插件与 Fluent SVG 图标所需插件。
    a.binaries = [
        e for e in a.binaries
        if not e[0].replace("\\", "/").startswith("PySide6/plugins/")
        or _KEEP_PLUGIN.match(e[0].replace("\\", "/"))
    ]
    # 剔除用不到的 Qt DLL 与 OpenGL 软件渲染器。
    a.binaries = [
        e for e in a.binaries if not _UNWANTED_BINARIES.search(e[0])
    ]
    # 翻译文件只保留中文与英文。
    a.datas = [
        e for e in a.datas
        if not e[0].replace("\\", "/").startswith("PySide6/translations/")
        or re.search(r"(_zh_CN|_en)\.qm$", e[0])
    ]
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='@NAME@',
    icon='@ICON@',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=@CONSOLE@,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''


def find_processes(exe_name: str) -> list[int]:
    """用 Windows tasklist 按进程名查找 PID。"""
    result = subprocess.run(
        ["tasklist", "/FI", f"IMAGENAME eq {exe_name}", "/FO", "CSV", "/NH"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    pids: list[int] = []
    for line in result.stdout.splitlines():
        parts = [part.strip('"') for part in line.split('","')]
        if len(parts) >= 2 and parts[0].casefold() == exe_name.casefold():
            try:
                pids.append(int(parts[1]))
            except ValueError:
                pass
    return pids


def kill_processes(pids: list[int]) -> None:
    """用 Windows taskkill 强制结束指定进程。"""
    for pid in pids:
        subprocess.run(["taskkill", "/PID", str(pid), "/F"], check=False)


def ensure_unlocked(no_kill: bool, assume_yes: bool) -> None:
    """确保 dist 中的 exe 没有被正在运行的实例占用。"""
    for exe_name, _name, _entry, _mode in TARGETS:
        pids = find_processes(exe_name)
        if not pids:
            continue
        print(f"{exe_name} is running (PID {', '.join(map(str, pids))}), "
              f"it locks dist\\{exe_name}.")
        if no_kill:
            sys.exit("Aborted: running executable blocks the build. "
                     "Close it or rerun without --no-kill.")
        if assume_yes:
            answer = "Y"
        else:
            answer = input(
                "Terminate it and continue? [Y/N, default Y]: "
            ).strip().upper() or "Y"
        if answer != "Y":
            sys.exit("Aborted, running executables were left untouched.")
        kill_processes(pids)


def generate_icon() -> Path:
    """从应用图像生成多尺寸 ICO 图标（16/24/32/48/64/128/256）。

    输出 ICO 内嵌 32bpp BMP 条目，兼容 Windows 资源管理器与任务栏。
    """
    from PySide6.QtCore import Qt
    from PySide6.QtGui import QGuiApplication, QImage, QPixmap

    from gui.appearance.logo import APP_ICON_PATH

    QGuiApplication.instance() or QGuiApplication([])

    sizes = (16, 24, 32, 48, 64, 128, 256)
    base = QPixmap(str(APP_ICON_PATH)).scaled(
        256, 256,
        Qt.AspectRatioMode.KeepAspectRatio,
        Qt.TransformationMode.SmoothTransformation,
    )

    entries: list[tuple[bytes, int]] = []  # (ICONDIRENTRY, offset)
    payload = bytearray()
    header_size = 6 + 16 * len(sizes)
    for size in sizes:
        pixmap = (
            base if size == 256 else base.scaled(
                size, size,
                Qt.AspectRatioMode.IgnoreAspectRatio,
                Qt.TransformationMode.SmoothTransformation,
            )
        )
        image = pixmap.toImage().convertToFormat(QImage.Format.Format_ARGB32)
        width, height = image.width(), image.height()
        raw = bytes(image.constBits())
        # BMP 行序自下而上；ARGB32 小端内存布局即 BGRA。
        row_stride = width * 4
        xor = bytearray()
        for y in range(height - 1, -1, -1):
            start = y * row_stride
            xor += raw[start:start + row_stride]
        and_row = ((width + 31) // 32) * 4
        bitmap = (
            struct.pack(
                "<IiiHHIIiiII",
                40, width, height * 2, 1, 32, 0, 0, 0, 0, 0, 0,
            )
            + xor
            + bytes(and_row * height)  # 32bpp 全透明 AND 掩码
        )
        entries.append((
            struct.pack(
                "<BBBBHHII",
                0 if size >= 256 else size,
                0 if size >= 256 else size,
                0, 0, 1, 32, len(bitmap), len(payload) + header_size,
            ),
            len(payload),
        ))
        payload += bitmap

    header = struct.pack("<HHH", 0, 1, len(sizes)) + b"".join(
        entry for entry, _offset in entries
    )
    ICON_PATH.parent.mkdir(parents=True, exist_ok=True)
    ICON_PATH.write_bytes(header + payload)
    return ICON_PATH


def collect_licenses() -> None:
    """收集项目与当前平台构建依赖的许可原文。"""
    destination = ROOT / "dist"
    destination.mkdir(exist_ok=True)
    for name in LEGAL_DOCUMENTS:
        shutil.copyfile(ROOT / name, destination / name)
    licenses = destination / "licenses"
    if licenses.exists():
        shutil.rmtree(licenses)
    if sys.platform == "win32":
        shutil.copytree(ROOT / "licenses", licenses)
        names = [
            "PySide6", "PySide6-Essentials", "PySide6-Addons", "shiboken6",
            "PySide6-Fluent-Widgets", "PySideSix-Frameless-Window", "darkdetect",
            "pywin32", "pyinstaller",
        ]
        if sys.version_info < (3, 11):
            names.append("tomli")
    else:
        licenses.mkdir()
        shutil.copyfile(ROOT / "licenses" / "Python-3.12.txt", licenses / "Python-3.12.txt")
        names = ["pyinstaller"]
    for name in names:
        distribution = metadata.distribution(name)
        for relative in distribution.files or ():
            if not any(
                part.lower().startswith(("license", "copying", "notice"))
                for part in relative.parts
            ):
                continue
            source = Path(distribution.locate_file(relative))
            if source.is_file():
                target = licenses / f"{name}-{distribution.version}" / Path(*(
                    part for part in relative.parts if part not in ("..", ".")
                ))
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)
    python_license = Path(sys.base_prefix) / "LICENSE.txt"
    if python_license.is_file():
        shutil.copyfile(python_license, licenses / "Python.txt")


def write_spec(name: str, entry: str, mode: str) -> Path:
    """生成 build\\<name>.spec，GUI 目标按过滤规则裁剪 Qt 文件。"""
    spec_path = ROOT / "build" / f"{name}.spec"
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    entry_rel = os.path.relpath((ROOT / entry).resolve(), spec_path.parent).replace("\\", "/")
    icon_rel = os.path.relpath(ICON_PATH, spec_path.parent).replace("\\", "/")
    data = [(str(ROOT / "dist" / document), ".") for document in LEGAL_DOCUMENTS]
    data.append((str(ROOT / "dist" / "licenses"), "licenses"))
    if mode == "--windowed":
        data.extend(
            (str(path), "gui/appearance/assets")
            for path in sorted((ROOT / "gui" / "appearance" / "assets").glob("*.png"))
        )
    content = (
        SPEC_TEMPLATE
        .replace("@ENTRY@", entry_rel)
        .replace("@ROOT@", repr(str(ROOT)))
        .replace("@DATA@", repr(data))
        .replace("@NAME@", name)
        .replace("@ICON@", icon_rel)
        .replace("@CONSOLE@", str(mode != "--windowed"))
        .replace("@SLIM@", str(mode == "--windowed"))
    )
    spec_path.write_text(content, encoding="utf-8")
    return spec_path


def run_pyinstaller(name: str, entry: str, mode: str) -> None:
    """以项目内缓存目录运行一次 PyInstaller 构建。"""
    env = os.environ.copy()
    env["PYINSTALLER_CONFIG_DIR"] = str(CACHE_DIR)
    spec_path = write_spec(name, entry, mode)
    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        str(spec_path),
    ]
    result = subprocess.run(command, cwd=ROOT, env=env)
    if result.returncode != 0:
        sys.exit(f"Failed building {name} (return code {result.returncode}).")


def build_linux_cli() -> None:
    """用 PyInstaller 构建自带 Python 运行时的 Linux CLI。"""
    env = os.environ.copy()
    env["PYINSTALLER_CONFIG_DIR"] = str(CACHE_DIR)
    command = [
        sys.executable, "-m", "PyInstaller", "--noconfirm", "--onefile", "--console",
        "--name", "nestpack-linux-cli", "--distpath", str(ROOT / "dist"),
        "--workpath", str(ROOT / "build" / "linux"),
        "--specpath", str(ROOT / "build"), "--paths", str(ROOT),
    ]
    for document in LEGAL_DOCUMENTS:
        command.extend(("--add-data", f"{ROOT / 'dist' / document}:."))
    command.extend(("--add-data", f"{ROOT / 'dist' / 'licenses'}:licenses"))
    command.append(str(ROOT / "cli" / "__main__.py"))
    result = subprocess.run(command, cwd=ROOT, env=env)
    if result.returncode != 0:
        sys.exit(f"Failed building nestpack-linux-cli (return code {result.returncode}).")


def main() -> int:
    parser = argparse.ArgumentParser(description="构建 Windows GUI/CLI 或 Linux CLI 单文件程序。")
    parser.add_argument(
        "--yes", action="store_true",
        help="terminate running executables without asking",
    )
    parser.add_argument(
        "--no-kill", action="store_true",
        help="fail instead of terminating running executables",
    )
    args = parser.parse_args()

    if sys.platform not in ("win32", "linux"):
        parser.error("NestPack 仅支持 Windows 与 Linux。")
    if sys.platform == "win32" and not (ROOT / ".venv" / "Scripts" / "python.exe").exists():
        print("WARNING: .venv not found; using current interpreter. "
              "Consider creating a virtual environment first.")
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("PyInstaller is not installed; installing ...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", "pyinstaller"],
            check=True,
        )

    if sys.platform == "win32":
        ensure_unlocked(args.no_kill, args.yes)
    collect_licenses()

    if sys.platform == "linux":
        build_linux_cli()
        print(f"已生成 {ROOT / 'dist' / 'nestpack-linux-cli'}")
        return 0

    icon_path = generate_icon()
    print(f"Generated icon: {icon_path}")

    total = len(TARGETS)
    for index, (exe_name, name, entry, mode) in enumerate(TARGETS, start=1):
        print(f"\n[{index}/{total}] Building {exe_name} ...")
        run_pyinstaller(name, entry, mode)

    print("\nBuild finished:")
    print(f"  {ROOT / 'dist' / TARGETS[0][0]}      GUI")
    print(f"  {ROOT / 'dist' / TARGETS[1][0]}  CLI")
    print("Default config is created next to each exe.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
